In [140]:
import pandas as pd

mainDf = pd.read_csv("./chemical.csv")
mainDf['PRIM_STA_C'] = mainDf['PRIM_STA_C'].str[:-4].apply(pd.to_numeric)

mainDf.head()

,PRIM_STA_C,SAMP_DATE,SAMP_TIME,LAB_NUM,ANADATE,INDATE,METHOD,INBY,SPECIAL,STORE_NUM,XMOD,FINDING
0,103039,11/22/17,848,4790,11/22/17,11/30/17,SM 212,#,S,00081,<,3.0
1,103039,11/22/17,848,4790,11/22/17,11/30/17,SM 215,#,S,00086,<,1.0
2,103039,11/22/17,848,4790,11/29/17,11/30/17,SM 251,#,S,00095,NaN,550.0
3,103039,11/22/17,848,4790,11/29/17,11/30/17,SM4500,#,S,00403,NaN,8.1
4,103039,11/22/17,848,4790,11/22/17,11/30/17,300.0,#,S,00618,NaN,5.7

In [145]:
mainDfSorted = mainDf.sort_values(by='SAMP_DATE', ascending=False).groupby(['PRIM_STA_C', 'STORE_NUM'], as_index=False).first()
mainDfSorted.to_json(path_or_buf="recentReport.json", orient='records')
#mainDfSorted.head()
# waterData['PARAMETER'].unique()

In [165]:
#now we must check if the finding is above or below threshold 

labeledChems = pd.read_csv("storetLabeled.csv")
labeledChems.head()
thresholdMainDf = pd.merge(mainDfSorted,labeledChems[['STORE_NUM', 'MCL', 'CHEMICAL__', 'PS']], on="STORE_NUM", how="left")
thresholdMainDf.head()
thresholdMainDf = thresholdMainDf.assign(result = (thresholdMainDf['FINDING'] > thresholdMainDf['MCL']))

thresholdMainDf.to_json(path_or_buf="recentReportFindings.json", orient='records')

In [173]:
thresholdMainDf.head()
thresholdMainDfFiltered = thresholdMainDf[thresholdMainDf.PS.notnull()]
thresholdMainDfFiltered.to_json(path_or_buf="recentReportFindingsPS.json", orient='records')
thresholdMainDfFiltered = thresholdMainDfFiltered[thresholdMainDfFiltered['result'] == True]
thresholdMainDfFiltered.head()
thresholdMainDfFiltered.to_json(path_or_buf="recentReportFindingsPSTrue.json", orient='records')

In [174]:
thresholdMainDfFiltered.head()

,PRIM_STA_C,STORE_NUM,SAMP_DATE,SAMP_TIME,LAB_NUM,ANADATE,INDATE,METHOD,INBY,SPECIAL,XMOD,FINDING,MCL,CHEMICAL__,PS,result
41,103040,11501,8/15/16,1255,4470,8/24/16,8/29/16,904.0,A,S,NaN,1.71,0.0,RADIUM 228,P,True
180,103040,A-072,8/15/16,1255,4470,8/24/16,8/29/16,900.0,A,S,NaN,1.11,0.0,GROSS ALPHA MDA95,P,True
182,103040,A-075,8/15/16,1255,4470,8/24/16,8/29/16,904.0,A,S,NaN,0.41,0.0,RADIUM 228 MDA95,P,True
184,103040,A-082,8/15/16,1255,4470,8/24/16,8/29/16,903.0,A,S,NaN,0.09,0.0,"RADIUM, TOTAL, MDA95-NTNC ONLY, BY 903.0",P,True
333,103041,82383,7/14/15,1240,5810,7/22/15,8/18/15,NaN,#,S,NaN,12.00,0.0,AGGRSSIVE INDEX (CORROSIVITY),S,True

In [21]:
import pandas as pd
import numpy as np
watsysDf = pd.read_csv("./watsys.csv", encoding='cp1252')
watsysDf = watsysDf[watsysDf.ADDRESS.notnull()]

print((watsysDf.loc[watsysDf['ADDRESS'] != None]))

      SYSTEM_NO                                SYSTEM_NAM  \
0       2800064                         DAKOTA SHY WINERY
1       5403214                                       NaN
2       4000829                         VINES R.V. RESORT
3       0103039              MOHRLAND MUTUAL WATER SYSTEM
4       0103040       NORRIS CANYON PROPERTY OWNERS ASSN.
5       0103041            TRAILER HAVEN MOBILE HOME PARK
9       0104001     WASHINGTON HOSPITAL HEALTHCARE SYSTEM
12      0104004                    U. S. PIPE AND FOUNDRY
14      0104010                       MORTON SALT COMPANY
15      0104012         VULCAN MATERIALS, CALMAT DIVISION
16      0104013                 PLEASANTON GRAVEL COMPANY
17      0104014                  HOSANNA HOMES - INACTIVE
18      0105002                         RIVERS END MARINA
19      0105003                         CEMEX/ELIOT PLANT
20      0105004                     MOUNTAIN HOUSE SCHOOL
21      0105006        HANSON AGGREGATE MID-PACIFIC, INC.
22      0105008          CASTLEWOOD DOMESTIC WATER SYSTEM
23      0105009                     MOUNTAIN HOUSE SCHOOL
24      0105010           EBRPD - DEL VALLE REGIONAL PARK
25      0105011       EBRPD - SHADOW CLIFFS REGIONAL PARK
27      0105013      EBRPD - REDWOOD SPRING REGIONAL PARK
28      0105014               EBRPD - GARIN REGIONAL PARK
29      0105015    EBRPD - MISSION PEAK REGIONAL PRESERVE
30      0105016                        MOUNTAIN HOUSE BAR
31      0105017                RANCHO LOS MOCHOS-BSA CAMP
32      0105018                  PURPLE ORCHID RESORT SPA
33      0105020                ALAMEDA COUNTY FAIRGROUNDS
34      0105021                MOUNTAIN HOUSE GOLF COURSE
35      0110001             ALAMEDA COUNTY WATER DISTRICT
36      0110003      CALIFORNIA WATER SERVICE - LIVERMORE
...         ...                                       ...
15023   5700523              BOGLE VINEYARDS TASTING ROOM
15024   1000641                     BAR 20 DAIRY DIGESTER
15025   4901452               QUARRYHILL BOTANICAL GARDEN
15026   5403153                   CIRCLE J - NORRIS RANCH
15027   5890004            LINDA COUNTY WD RECYCLED WATER
15028   3301176  GRIMMWAY ENTERPRISES - CAL ORGANIC THERM
15029   3600490                     CRAB FLATS CAMPGROUND
15030   4901453                     MAURITSON LABOR HOUSE
15031   3610131           CALTRANS-MOUNTAIN PASS JPOE AIS
15032   5700617          MARIANI NUT COMPANY - BUCKEYE RD
15033   2000962                          THE MANOR ESTATE
15034   5403215                         FRESH SELECT, LLC
15035   5105014                                 HOLT 7518
15036   4301014             ALMA LATTER-DAY SAINTS CHURCH
15037   2300955                   BOONVILLE GENERAL STORE
15038   4901455                          APERTURE CELLARS
15039   4810037               SOLANO COUNTY CORDELIA SITE
15040   2000963                  MADERA VALLEY MARKET, LP
15041   0300113         C. G. DI ARIE VINEYARD AND WINERY
15042   4901451                          SPIDER WEB RANCH
15043   1503685                CALIFIA FARMS WATER SYSTEM
15044   3601184    MOJAVE SOLAR PROJECT ALPHA POWER PLANT
15045   3601185     MOJAVE SOLAR PROJECT BETA POWER PLANT
15046   3902194   CHEROKEE MEMORIAL PARK INC WATER SYSTEM
15047   3400473               METRO AIR PARK WATER SYSTEM
15048   0105019                          SUNOL SUPER STOP
15050   3107345                            KINGVALE SHELL
15051   3107347                              RIEGO MARKET
15052   1000644                   IMMANUEL SPORTS COMPLEX
15053   1504009                          ARCO AMPM #42924

                               HQNAME                             ADDRESS  \
0                                 NaN                771 Sage Canyon Road
1      THREE RIVERS HISTORICAL MUSEUM                     42268 SIERRA DR
2                                 NaN                         88 WELLSONA
3                     MOHRLAND MUTUAL                    24927 Mohr Drive
4                     NORRIS CANYON P             8653 Norris Canyon Road
5                     TRAILER HAVEN M        2399 East 14th Street SPC 28
9                     WASHINGTON HOSP                   2000 Mowry Avenue
12                     U. S. PIPE AND                   1295 Whipple Road
14                    MORTON SALT COM                  7380 Morton Avenue
15                    VULCAN MATERIAL              365 No Canyons Parkway
16                    PLEASANTON GRAV                        P.O. Box 850
17                                NaN                 9990 Crow Canyon Rd
18                    RIVERS END MARI                    Route 1, Box 22A
19                    RMC-LONESTAR EL           5180 Golden Hills Parkway
20                                NaN                  25165 FLANDERS DR.
21                    HANSON PERMANEN                     3000 Busch Road
22                    CASTLEWOOD COUN             707 Country Club Circle
23                     MOUNTAIN HOUSE            3950 Mountain House Road
24                    EBRPD - DEL VAL                 7000 Del Valle Road
25                     EBRPD - SHADOW                       Stanley Blvd.
27                    EBRPD - REDWOOD                        Redwood Road
28                    EBRPD - GARIN R                   End of Garin Road
29                    EBRPD - MISSION                       P.O. Box 5381
30                     MOUNTAIN HOUSE                  8351 Rinuaro Court
31                                NaN               16784 W GRANT LINE RD
32                                NaN                       4549 Cross Rd
33                     ALAMEDA COUNTY                 4501 Pleasanton Ave
34                     MOUNTAIN HOUSE              15000 Altamont Pass Rd
35                     ALAMEDA COUNTY                       P.O. Box 5110
36                      CWS LIVERMORE                  195 South N Street
...                               ...                                 ...
15023                             NaN                   49762 HAMILTON RD
15024                             NaN        24387 W. Whitesbridge Avenue
15025                    P.O. Box 232                12841 Sonoma Highway
15026                             NaN           41893 YOKOHL VALLEY DRIVE
15027                             NaN                  1280 Scales Street
15028                             NaN                   54895 FILLMORE ST
15029                             NaN                602 S Tippecanoe Ave
15030                             NaN              5061 E. Soda Rock Lane
15031                             NaN             1220 N Street, Room 116
15032                             NaN                   709 Dutton Street
15033                             NaN                      34614 Avenue 9
15034                             NaN                       39303 ROAD 56
15035                             NaN                    7310 Pacific Ave
15036                             NaN                   23185 Summit Road
15037                             NaN                         P.O.Box 653
15038                             NaN           12295 Old Redwood Highway
15039                             NaN           675 TEXAS STREET STE 2500
15040                             NaN                       18463 Road 23
15041                             NaN                   5200 Di Arie Road
15042                             NaN  475 Aviation Boulevard - Suite 120
15043                             NaN                     33502 Lerdo Hwy
15044                             NaN                42134 Happer Lake Rd
15045                             NaN                42134 Happer Lake Rd
15046                             NaN                14165 N BECKMAN ROAD
15047                             NaN                     10151 Florin Rd
15048                             NaN                     3004 ANDRADE RD
15050                             NaN                           PO BOX 61
15051                             NaN              8000 PLEASANT GROVE RD
15052                             NaN                         42675 Rd 44
15053                             NaN                  20404 TAFT HIGHWAY

                 CITY STATE    ZIP ZIP_EXT  POP_SERV  CONNECTION  \
0          ST. HELENA    CA  94574     NaN      30.0         1.0
1        THREE RIVERS    CA  93271     NaN      25.0         2.0
2             PASO RO    CA  93446     NaN     400.0         1.0
3             HAYWARD    CA  94545      tt     116.0        99.0
4       CASTRO VALLEY    CA  94552       S      50.0        19.0
5         SAN LEANDRO    CA  94577    6058     543.0       200.0
9             FREMONT    CA  94538     538       0.0         1.0
12         UNION CITY    CA  94587    rich       0.0         0.0
14             NEWARK    CA  94560     560      10.0         1.0
15          LIVERMORE    CA  94551     551      45.0         3.0
16         PLEASANTON    CA  94566     566      26.0         4.0
17      CASTRO VALLEY    CA  94552    9698       0.0         2.0
18      DISCOVERY BAY    CA  94505    1951     250.0         4.0
19         PLEASANTON    CA  94566    6308      70.0         1.0
20             CARMEL    CA  93923     NaN       0.0         0.0
21         PLEASANTON    CA  94566     566      78.0         1.0
22         PLEASANTON    CA  94566     NaN     499.0       194.0
23              BYRON    CA  94514     NaN      24.0         3.0
24          LIVERMORE    CA  94605     605   10000.0       101.0
25         PLEASANTON    CA  94566     566     593.0         2.0
27            OAKLAND    CA  94605     605      35.0         6.0
28            HAYWARD    CA  94544     544      40.0         7.0
29            OAKLAND    CA  94605    0381      10.0         1.0
30              TRACY    CA  95391    9210      25.0         1.0
31              TRACY    CA  95391    9602     600.0         1.0
32          Livermore    CA  94550     NaN      45.0         0.0
33         PLEASANTON    CA  94566    7001      82.0         3.0
34     MOUNTAIN HOUSE    CA  95391     NaN       0.0         1.0
35            FREMONT    CA  94537     537  340000.0     82487.0
36          LIVERMORE    CA  94550    4350   56700.0     18043.0
...               ...   ...    ...     ...       ...         ...
15023      CLARKSBURG    CA  95612     NaN     225.0         4.0
15024          KERMAN    CA  93630     NaN      95.0         2.0
15025      GLEN ELLEN    CA  95442     NaN      50.0         2.0
15026     SPRINGVILLE    CA  93265     NaN      25.0         1.0
15027      MARYSVILLE    CA  95901     NaN       0.0         1.0
15028         THERMAL    CA  92274     NaN     126.0         1.0
15029  SAN BERNARDINO    CA  92408     NaN     100.0         1.0
15030      HEALDSBURG    CA  95448     NaN      35.0         1.0
15031      SACRAMENTO    CA  95814     NaN       1.0         1.0
15032         WINTERS    CA  95694     NaN      50.0         5.0
15033          MADERA    CA  93636     NaN     152.0         2.0
15034          DINUBA    CA  93618     NaN      30.0         3.0
15035  PLEASANT GROVE    CA  95668     NaN      25.0         1.0
15036       LOS GATOS    CA  95033     NaN      40.0         1.0
15037         KENWOOD    CA  95452     NaN      40.0         3.0
15038      HEALDSBURG    CA  95448     NaN      26.0         1.0
15039       FAIRFIELD    CA  94533     NaN      30.0         1.0
15040          MADERA    CA  93637     NaN     500.0         1.0
15041        Mt Aukum    CA  95656     NaN      25.0         5.0
15042      SANTA ROSA    CA  95403     NaN      32.0         1.0
15043     BAKERSFIELD    CA  93308     NaN     120.0         1.0
15044         HINKLEY    CA  92347     NaN      25.0         1.0
15045         HINKLEY    CA  92347     NaN      25.0         1.0
15046            LODI    CA  95240     NaN     300.0         6.0
15047      SACRAMENTO    CA  95829     NaN    1500.0       300.0
15048           SUNOL    CA  94586    9453     155.0         1.0
15050    EMIGRANT GAP    CA  95715     NaN      25.0         1.0
15051         ELVERTA    CA  95626     NaN      25.0         1.0
15052         REEDLEY    CA  93654     NaN      25.0         1.0
15053     BAKERSFIELD    CA  93311     NaN      25.0         1.0

                                  AREA_SERVE
0                                        NaN
1                                        NaN
2                                        NaN
3                                        NaN
4                                        NaN
5              Trailer Haven Mobilehome Park
9      Washington Hospital Healthcare System
12                                       NaN
14                       Morton Salt Company
15             Vulcan Materials, CalMat Div.
16                                       NaN
17                              Verne Teyler
18                                       NaN
19         RMC-Lonestar Eliot Agregate Plant
20                                       NaN
21                                       NaN
22                                       NaN
23                                       NaN
24                                       NaN
25                                       NaN
27                                       NaN
28                                       NaN
29                                       NaN
30                             Josie Alvarez
31                                       NaN
32                                       NaN
33                Alameda County Fairgrounds
34                Mountain House Golf Course
35                 FREMONT NEWARK,UNION CITY
36                                 LIVERMORE
...                                      ...
15023                                    NaN
15024                                    NaN
15025                                    NaN
15026                                    NaN
15027                   WASTEWATER GENERATOR
15028                                    NaN
15029                                    NaN
15030                                    NaN
15031                                    NaN
15032                                    NaN
15033                                    NaN
15034                                    NaN
15035                                    NaN
15036                                    NaN
15037                                    NaN
15038                                    NaN
15039                                    NaN
15040                                    NaN
15041                                    NaN
15042                                    NaN
15043                                    NaN
15044                                    NaN
15045                                    NaN
15046                                    NaN
15047                                    NaN
15048                                    NaN
15050                                    NaN
15051                                    NaN
15052                                    NaN
15053                                    NaN

[13374 rows x 11 columns]

In [23]:
editDf = pd.read_json("waterSources.json")

In [27]:
editDf.head()
editDf.to_json(path_or_buf="waterSourcesEdit.json", orient='records')

In [28]:
editDf.head()

,ADDRESS,SYSTEM_NAM,SYSTEM_NO,latitude,longitude
0,771 Sage Canyon Road,DAKOTA SHY WINERY,2800064,-0.756883,-0.074388
1,42268 SIERRA DR,None,5403214,0.920697,0.079701
10,None,PYZER WATER SYSTEM,0104002,0.729870,2.194797
100,650 O STREET,BLUE LAKE MIDDLE HAND PUMP,0202553,0.902110,-1.281821
1000,P.O. BOX Y,CALIFORNIA CONSERVATION CORPS,0900657,0.810329,-2.018473

In [71]:
activeViol = pd.read_csv("active.csv")

In [72]:
activeViol.head()
activeViolSorted = activeViol.sort_values(by='VIOL_END_DATE', ascending=False).groupby(['WATER_SYSTEM_NUMBER', 'ANALYTE_NAME'], as_index=False).first()

activeViolSorted.to_json(path_or_buf="activeViolations.json", orient='records')

In [178]:
activeViol = pd.read_json("activeViolations.json", orient='records')
activeViol['WATER_SYSTEM_NUMBER'] = activeViol['WATER_SYSTEM_NUMBER'].str[2:]
activeViol['WATER_SYSTEM_NUMBER'] = activeViol['WATER_SYSTEM_NUMBER'].apply(pd.to_numeric)
recentReportDf = pd.read_json("recentReport.json", orient='records')

recentReport = pd.read_json("recentReportFindingsPSTrue.json", orient='records')

sysList = pd.read_json("example.json", orient='records')
sysList['SYSTEM_NO'] = sysList['SYSTEM_NO'].apply(pd.to_numeric)
numList = sysList.SYSTEM_NO.unique()
sysNumViols = activeViol.loc[activeViol['WATER_SYSTEM_NUMBER'].isin(numList)]

report = dict((el,"No violations!") for el in numList)
for idx, row in sysNumViols.iterrows():
    date = str(row['ENF_ACTION_ISSUE_DATE'])
    if (report[row['WATER_SYSTEM_NUMBER']] == "No violations!"):
        report[row['WATER_SYSTEM_NUMBER']] = str("Violation Number: "+str(row['VIOLATION_NUMBER'])+", Violation Type: "+str(row['VIOLATION_TYPE_NAME'])+", Chemical: "+str(row['ANALYTE_NAME'])+", Result: "+str(row['RESULT'])+", MCL: "+str(row['MCL'])+", Action issued: "+str(row['ENF_ACTION_TYPE_ISSUED'])+", Action Issue Date: " + date)
    else:
        report[row['WATER_SYSTEM_NUMBER']] += str("\nViolation Number: "+str(row['VIOLATION_NUMBER'])+", Violation Type: "+str(row['VIOLATION_TYPE_NAME'])+", Chemical: "+str(row['ANALYTE_NAME'])+", Result: "+str(row['RESULT'])+", MCL: "+str(row['MCL'])+", Action issued: "+str(row['ENF_ACTION_TYPE_ISSUED'])+", Action Issue Date: "+date)

for sysNum in numList:
    recentData = recentReport[recentReport['PRIM_STA_C'] == sysNum]
    for idx, row in recentData.iterrows():
        if (report[sysNum] == "No violations!"):
            report[sysNum] = str("Chemical: "+str(row['CHEMICAL__'])+", Finding: " +str(row['FINDING'] )+", MCL: "+ str(row['MCL']))
        else:
            report[sysNum] += str("Chemical: "+str(row['CHEMICAL__'])+", Finding: " +str(row['FINDING'] )+", MCL: "+ str(row['MCL']))


print(report)


#return an dict of report objects for each system number 
#report = {12092138: "no violation", 3149814: "violation info with chemicals"}
#containing strings

{202501: 'Chemical: PH, FIELD, Finding: 6.77, MCL: 0.0Chemical: LEAD, Finding: 5.0, MCL: 0.0Chemical: RADIUM 228, Finding: 1.69, MCL: 0.0Chemical: GROSS ALPHA MDA95, Finding: 2.42, MCL: 0.0Chemical: RADIUM 228 MDA95, Finding: 1.0, MCL: 0.0Chemical: GROSS BETA MDA95, Finding: 0.65, MCL: 0.0', 202502: 'No violations!', 202503: 'No violations!', 202504: 'Chemical: AGGRSSIVE INDEX (CORROSIVITY), Finding: 12.0, MCL: 0.0', 202505: 'No violations!', 202506: 'No violations!', 202251: 'No violations!', 202508: 'Chemical: ARSENIC, Finding: 22.0, MCL: 10.0', 202509: 'No violations!', 202512: 'No violations!', 202513: 'No violations!', 202515: 'No violations!', 202516: 'No violations!', 202517: 'No violations!', 202519: 'No violations!', 202520: 'Chemical: NITRITE (AS N), Finding: 10.0, MCL: 1.0Chemical: NITRATE + NITRITE (AS N), Finding: 16.0, MCL: 10.0', 202521: 'No violations!', 202522: 'Chemical: NITRITE (AS N), Finding: 10.0, MCL: 1.0Chemical: NITRATE + NITRITE (AS N), Finding: 416.0, MCL: 10.0Chemical: GROSS ALPHA MDA95, Finding: 2.83, MCL: 0.0Chemical: RADIUM 226 MDA95, Finding: 0.40700000000000003, MCL: 0.0Chemical: RADIUM 228 MDA95, Finding: 0.7000000000000001, MCL: 0.0Chemical: GROSS BETA MDA95, Finding: 1.44, MCL: 0.0', 202523: 'No violations!', 202524: 'No violations!', 202525: 'No violations!', 202529: 'No violations!', 202530: 'Chemical: NITRITE (AS N), Finding: 20.0, MCL: 1.0Chemical: NITRATE + NITRITE (AS N), Finding: 61.0, MCL: 10.0', 202531: 'No violations!', 202532: 'No violations!', 202550: 'No violations!', 190001: 'No violations!', 201000: 'No violations!', 201001: 'No violations!', 105002: 'No violations!', 105003: 'Chemical: RADIUM 226, Finding: 0.61, MCL: 0.0Chemical: RADIUM 228, Finding: 0.8200000000000001, MCL: 0.0Chemical: GROSS ALPHA MDA95, Finding: 0.49, MCL: 0.0Chemical: RADIUM 226 MDA95, Finding: 0.07, MCL: 0.0Chemical: RADIUM 228 MDA95, Finding: 0.12, MCL: 0.0', 105004: 'No violations!', 105010: 'Chemical: LEAD, Finding: 5.0, MCL: 0.0', 105006: 'No violations!', 202543: 'No violations!', 105008: 'No violations!', 105009: 'Chemical: FLUORIDE (F) (NATURAL-SOURCE), Finding: 3.3, MCL: 2.0Chemical: GROSS ALPHA, Finding: 15.42, MCL: 15.0Chemical: TOTAL DISSOLVED SOLIDS, Finding: 1200.0, MCL: 1000.0Chemical: GROSS ALPHA MDA95, Finding: 0.05, MCL: 0.0', 190002: 'No violations!', 190003: 'No violations!', 105012: 'Chemical: NITRITE (AS N), Finding: 400.0, MCL: 1.0Chemical: NITRATE + NITRITE (AS N), Finding: 400.0, MCL: 10.0', 105013: 'Chemical: NITRITE (AS N), Finding: 400.0, MCL: 1.0Chemical: NITRATE + NITRITE (AS N), Finding: 400.0, MCL: 10.0', 190006: 'No violations!', 105015: 'No violations!', 105016: 'Chemical: NITRITE (AS N), Finding: 400.0, MCL: 1.0', 190004: 'No violations!', 110650: 'Chemical: LEAD, Finding: 0.5, MCL: 0.0', 105020: 'Chemical: TETRACHLOROETHYLENE, Finding: 10.5, MCL: 5.0Chemical: GROSS ALPHA MDA95, Finding: 0.13, MCL: 0.0', 105021: 'No violations!', 190005: 'No violations!', 104001: 'No violations!', 104002: 'No violations!', 104003: 'No violations!', 104004: 'No violations!', 105014: 'No violations!', 104006: 'No violations!', 104010: 'Chemical: COLOR, Finding: 80.0, MCL: 15.0Chemical: NITRITE (AS N), Finding: 400.0, MCL: 1.0Chemical: CHLORIDE, Finding: 720.0, MCL: 500.0Chemical: IRON, Finding: 7000.0, MCL: 300.0Chemical: MANGANESE, Finding: 460.0, MCL: 50.0Chemical: RADIUM 226, Finding: 1.0, MCL: 0.0Chemical: RADIUM 228, Finding: 1.0, MCL: 0.0Chemical: TOTAL DISSOLVED SOLIDS, Finding: 1600.0, MCL: 1000.0Chemical: TURBIDITY, LABORATORY, Finding: 98.0, MCL: 5.0Chemical: AGGRSSIVE INDEX (CORROSIVITY), Finding: 12.58, MCL: 0.0Chemical: GROSS ALPHA MDA95, Finding: 0.1, MCL: 0.0Chemical: RADIUM 226 MDA95, Finding: 1.45, MCL: 0.0Chemical: RADIUM 228 MDA95, Finding: 0.76, MCL: 0.0Chemical: GROSS BETA MDA95, Finding: 1.54, MCL: 0.0', 190007: 'No violations!', 104012: 'No violations!', 104013: 'No violations!', 5403214: 'No violations!', 202552: 'Chemical: NITRITE (AS N), Finding: 10.0, MCL: 1.0', 190008: 'No violations!', 105017: 'No violations!', 105018: 'Chemical: AGGRSSIVE INDEX (CORROSIVITY), Finding: 11.95, MCL: 0.0', 202547: 'Chemical: NITRATE + NITRITE (AS N), Finding: 400.0, MCL: 10.0', 110700: 'No violations!', 4000829: 'No violations!', 202542: 'No violations!', 103039: 'No violations!', 103040: 'Chemical: RADIUM 228, Finding: 1.71, MCL: 0.0Chemical: GROSS ALPHA MDA95, Finding: 1.11, MCL: 0.0Chemical: RADIUM 228 MDA95, Finding: 0.41000000000000003, MCL: 0.0Chemical: RADIUM, TOTAL, MDA95-NTNC ONLY, BY 903.0, Finding: 0.09, MCL: 0.0', 103041: 'Chemical: AGGRSSIVE INDEX (CORROSIVITY), Finding: 12.0, MCL: 0.0Chemical: GROSS ALPHA MDA95, Finding: 1.6400000000000001, MCL: 0.0', 103046: 'No violations!', 103049: 'No violations!', 103050: 'No violations!', 202546: 'No violations!', 202551: 'No violations!', 110001: 'Chemical: PH, FIELD, Finding: 7.9, MCL: 0.0Chemical: RADIUM 226, Finding: 1.0, MCL: 0.0Chemical: RADIUM 228, Finding: 1.0, MCL: 0.0Chemical: TURBIDITY, FIELD, Finding: 1.7000000000000002, MCL: 0.0Chemical: AGGRSSIVE INDEX (CORROSIVITY), Finding: 11.4, MCL: 0.0Chemical: NITRATE + NITRITE (AS N), Finding: 2240.0, MCL: 10.0Chemical: GROSS ALPHA MDA95, Finding: 0.16, MCL: 0.0Chemical: RADIUM 226 MDA95, Finding: 0.45, MCL: 0.0Chemical: RADIUM 228 MDA95, Finding: 0.84, MCL: 0.0Chemical: GROSS BETA MDA95, Finding: 3.0, MCL: 0.0', 110003: 'Chemical: PH, FIELD, Finding: 7.52, MCL: 0.0Chemical: RADIUM 226, Finding: 1.0, MCL: 0.0Chemical: RADIUM 228, Finding: 1.0, MCL: 0.0Chemical: AGGRSSIVE INDEX (CORROSIVITY), Finding: 13.0, MCL: 0.0Chemical: GROSS ALPHA MDA95, Finding: 0.7000000000000001, MCL: 0.0Chemical: RADIUM 226 MDA95, Finding: 0.47000000000000003, MCL: 0.0Chemical: RADIUM 228 MDA95, Finding: 0.87, MCL: 0.0', 110005: 'Chemical: PH, FIELD, Finding: 7.9, MCL: 0.0Chemical: NITRITE (AS N), Finding: 400.0, MCL: 1.0Chemical: LEAD, Finding: 5.0, MCL: 0.0Chemical: RADIUM 226, Finding: 0.048, MCL: 0.0Chemical: RADIUM 228, Finding: 0.058, MCL: 0.0Chemical: AGGRSSIVE INDEX (CORROSIVITY), Finding: 12.0, MCL: 0.0Chemical: NITRATE + NITRITE (AS N), Finding: 400.0, MCL: 10.0Chemical: FLUORIDE (TREATMENT RELATED-DISTRIBUTION), Finding: 0.74, MCL: 0.0Chemical: GROSS ALPHA MDA95, Finding: 0.8140000000000001, MCL: 0.0Chemical: RADIUM 226 MDA95, Finding: 0.363, MCL: 0.0Chemical: RADIUM 228 MDA95, Finding: 0.253, MCL: 0.0Chemical: GROSS BETA MDA95, Finding: 1.23, MCL: 0.0Chemical: RADIUM, TOTAL, MDA95-NTNC ONLY, BY 903.0, Finding: 0.47000000000000003, MCL: 0.0', 110006: 'No violations!', 110008: 'Chemical: AGGRSSIVE INDEX (CORROSIVITY), Finding: 12.0, MCL: 0.0Chemical: NITRATE + NITRITE (AS N), Finding: 4100.0, MCL: 10.0Chemical: GROSS ALPHA MDA95, Finding: 2.15, MCL: 0.0', 110009: 'No violations!', 110010: 'Chemical: PH, FIELD, Finding: 7.2, MCL: 0.0Chemical: RADIUM 226, Finding: 1.0, MCL: 0.0Chemical: RADIUM 228, Finding: 1.0, MCL: 0.0Chemical: TURBIDITY, FIELD, Finding: 3.5, MCL: 0.0Chemical: AGGRSSIVE INDEX (CORROSIVITY), Finding: 12.1, MCL: 0.0Chemical: NITRATE + NITRITE (AS N), Finding: 190.0, MCL: 10.0Chemical: GROSS ALPHA MDA95, Finding: 0.15, MCL: 0.0Chemical: RADIUM 226 MDA95, Finding: 0.41000000000000003, MCL: 0.0Chemical: RADIUM 228 MDA95, Finding: 0.9500000000000001, MCL: 0.0Chemical: GROSS BETA MDA95, Finding: 1.6, MCL: 0.0', 110011: 'No violations!', 110012: 'Chemical: NITRITE (AS N), Finding: 400.0, MCL: 1.0Chemical: LEAD, Finding: 5.0, MCL: 0.0Chemical: NITRATE + NITRITE (AS N), Finding: 400.0, MCL: 10.0', 110013: 'No violations!', 110014: 'No violations!', 110015: 'No violations!', 2800064: 'No violations!', 110017: 'No violations!', 110018: 'Chemical: NITRITE (AS N), Finding: 400.0, MCL: 1.0Chemical: LEAD, Finding: 5.0, MCL: 0.0Chemical: RADIUM 226, Finding: 1.0, MCL: 0.0Chemical: RADIUM 228, Finding: 1.0, MCL: 0.0Chemical: NITRATE + NITRITE (AS N), Finding: 2781.0, MCL: 10.0Chemical: GROSS ALPHA MDA95, Finding: 0.16, MCL: 0.0Chemical: RADIUM 226 MDA95, Finding: 0.49, MCL: 0.0Chemical: RADIUM 228 MDA95, Finding: 0.84, MCL: 0.0Chemical: GROSS BETA MDA95, Finding: 1.9, MCL: 0.0', 110019: 'No violations!', 110020: 'No violations!', 105011: 'No violations!', 104014: 'No violations!', 202548: 'No violations!', 190009: 'No violations!', 110016: 'No violations!', 202549: 'Chemical: NITRITE (AS N), Finding: 50.0, MCL: 1.0Chemical: NITRATE + NITRITE (AS N), Finding: 200.0, MCL: 10.0', 201002: 'No violations!'}

In [180]:
recentReport.shape

(3485, 16)

{202501: 'No violations!', 202502: 'No violations!', 202503: 'No violations!', 202504: 'No violations!', 202505: 'No violations!', 202506: 'No violations!', 202251: 'No violations!', 202508: 'No violations!', 202509: 'No violations!', 202512: 'No violations!', 202513: 'No violations!', 202515: 'No violations!', 202516: 'No violations!', 202517: 'No violations!', 202519: 'No violations!', 202520: 'No violations!', 202521: 'No violations!', 202522: 'No violations!', 202523: 'No violations!', 202524: 'No violations!', 202525: 'No violations!', 202529: 'No violations!', 202530: 'No violations!', 202531: 'No violations!', 202532: 'No violations!', 202550: 'No violations!', 190001: 'No violations!', 201000: 'No violations!', 201001: 'No violations!', 105002: 'No violations!', 105003: 'No violations!', 105004: 'No violations!', 105010: 'No violations!', 105006: 'No violations!', 202543: 'No violations!', 105008: 'No violations!', 105009: 'No violations!', 190002: 'No violations!', 190003: 'No violations!', 105012: 'No violations!', 105013: 'No violations!', 190006: 'No violations!', 105015: 'No violations!', 105016: 'No violations!', 190004: 'No violations!', 110650: 'No violations!', 105020: 'No violations!', 105021: 'No violations!', 190005: 'No violations!', 104001: 'No violations!', 104002: 'No violations!', 104003: 'No violations!', 104004: 'No violations!', 105014: 'No violations!', 104006: 'No violations!', 104010: 'No violations!', 190007: 'No violations!', 104012: 'No violations!', 104013: 'No violations!', 5403214: 'No violations!', 202552: 'No violations!', 190008: 'No violations!', 105017: 'No violations!', 105018: 'No violations!', 202547: 'No violations!', 110700: 'No violations!', 4000829: 'No violations!', 202542: 'No violations!', 310004: 'Violation Number: 9910019, Violation Type: MCL, LRAA, Chemical: TTHM, Result: 0.081 MG/L, MCL: 0.080 MG/L, Action issued: FORMAL ENFORCEMENT ACTION ISSUED, Action Issue Date: 2017-08-03', 103039: 'No violations!', 103040: 'No violations!', 103041: 'No violations!', 103046: 'No violations!', 900673: 'Violation Number: 2, Violation Type: MCL,  AVERAGE, Chemical: COMBINED URANIUM, Result: 43 PCI/L, MCL: 20 PCI/L, Action issued: FORMAL ENFORCEMENT ACTION ISSUED, Action Issue Date: 2017-09-07\nViolation Number: 1, Violation Type: MCL,  AVERAGE, Chemical: GROSS ALPHA PARTICLE ACTIVITY, Result: 40 PCI/L, MCL: 15 PCI/L, Action issued: FORMAL ENFORCEMENT ACTION ISSUED, Action Issue Date: 2017-09-07', 103049: 'No violations!', 103050: 'No violations!', 202546: 'No violations!', 202551: 'No violations!', 110001: 'No violations!', 110003: 'No violations!', 110005: 'No violations!', 110006: 'No violations!', 110008: 'No violations!', 110009: 'No violations!', 110010: 'No violations!', 110011: 'No violations!', 110012: 'No violations!', 110013: 'No violations!', 110014: 'No violations!', 110015: 'No violations!', 2800064: 'No violations!', 110017: 'No violations!', 110018: 'No violations!', 110019: 'No violations!', 110020: 'No violations!', 105011: 'No violations!', 104014: 'No violations!', 202548: 'No violations!', 190009: 'No violations!', 110016: 'No violations!', 202549: 'No violations!', 201002: 'No violations!'}

In [183]:
watsysDf = pd.read_csv("watsys.csv", encoding='cp1252')
watsysDf = watsysDf.drop_duplicates(subset='SYSTEM_NO')
watsysDf.shape

(15054, 11)